baseurl = "http://lucumt.info"
languageCode = "zh-CN"
title = "飞狐的部落格"
canonifyurls = true
PygmentsCodeFences=true
disqusShortname = "rosenlu"

[author]
    name = "Tom Maiaroto"
    homepage = "http://lucumt.info"

[params] 
    sidebartitle = "飞狐的部落格" 
    sidebartagline = "Rosen Lu"
    photo = "/img/photo.jpg"
    highlightstyle="foundation"

[[menu.main]] 
    pre = "<i class='fa fa-road'></i>"
    name = "About" 
    url = "/about"

[[menu.main]] 
    pre = "<i class='fa fa-road'></i>"
    name = "Blog" 
    url = "/posts"

[[menu.footer]] 
    name = "Designed by Red Lounge" 
    url = "https://github.com/tmaiaroto/hugo-redlounge"

[[menu.social]] 
    pre = "<i class='fa fa-mail-forward'></i>" 
    url = "mailto:lucumt@gmail.com" 
    identifier = "mail-forward"
    weight = 100

[[menu.social]] 
    pre = "<i class='fa fa-twitter'></i>" 
    url = "http://www.twitter.com/rosenlucumt" 
    identifier = "twitter"
    weight = -7

[[menu.social]] 
    pre = "<i class='fa fa-facebook'></i>" 
    url = "https://www.facebook.com/rosen.lu.1" 
    identifier = "facebook"
    weight = -8

[[menu.social]] 
    pre = "<i class='fa fa-google-plus'></i>" 
    url = "https://plus.google.com/u/0/115794588502118898127/posts" 
    identifier = "google-plus"
    weight = -9

[[menu.social]] 
    pre = "<i class='fa fa-github'></i>" 
    url = "https://github.com/lucumt" 
    identifier = "github"
    weight = -10

 [[menu.site]]
    url ="http://lilydjwg.is-programmer.com/"
    name = "依云的博客"
    weight = -20

 [[menu.site]]
    url = "http://evilbinary.org/"
    name = "邪恶二进制"
    weight = -19

 [[menu.site]]
    url = "http://www.wlman.cc/"
    name = "Consec 's Blog"
    weight = 7
 
 [[menu.site]]
    url ="http://www.linuxzen.com/"
    name = "cold's world"
    weight = 8

  [[menu.site]]
    url = "http://frantic1048.logdown.com/"
    name = "Frantic log#1048"
    weight = 9